---
# =============================================================================
# tessella-client â€“ Handler
# =============================================================================

- name: restart display-manager
  ansible.builtin.systemd:
    name: display-manager.service
    state: restarted
